/**
 * Represents a file or directory in the processed file tree.
 * This structure is generated by the WASM module.
 */
export interface FileNode {
    path: string;
    name: string;
    is_dir: boolean;
    children: FileNode[];
    token_count?: number; // Populated if `showTokenCount` setting is true
    size?: number;
}

/**
 * The result object returned by the WASM `process_files` function.
 */
export interface ProcessingResult {
    file_tree: FileNode[];
    total_tokens: number;
    total_files: number;
    total_size: number;
    processing_time_ms: number;
}

/**
 * Represents a single file's content, used as input for processing.
 */
export interface FileInput {
    path: string;
    content: string;
}

/**
 * Lightweight file information used for the initial filtering pass.
 */
export interface FileMetadata {
    path: string;
    size: number;
}

/**
 * Defines the possible modes for the VIM keybindings.
 */
export type VimMode = 'normal' | 'visual';

/**
 * User-configurable settings that control application behavior.
 * This is the primary settings object stored in Zustand and configured in the UI.
 * It's a superset of the options passed to the WASM module.
 */
export interface Settings {
    // --- Processing Options ---
    hideEmptyFolders: boolean;
    showTokenCount: boolean;
    // --- Filter Options ---
    maxFileSize: number; // in bytes
}

// --- WASM Function Options ---

/**
 * Options specifically for the WASM `process_files` function.
 * Derived from the main `Settings` object.
 */
export interface ProcessingOptions {
    hide_empty_folders: boolean;
    show_token_count: boolean;
}

/**
 * Options specifically for the WASM `filter_files` function.
 * Derived from the main `Settings` object.
 */
export interface FilterOptions {
    text_only: boolean;
    max_file_size: number; // in bytes
}

/**
 * Options for the WASM `merge_files_to_markdown` function.
 */
export interface MarkdownOptions {
    include_path_headers?: boolean;
}
